package com.example.expensees.models

import android.net.Uri
import com.google.gson.annotations.SerializedName


enum class BudgetStatus {
    PENDING, APPROVED, DENIED
}

data class ExpenseItem(
    val category: String,
    val quantity: Int,
    val amountPerUnit: Double,
    val remarks: String = ""
)

data class SubmittedBudget(
    val name: String,
    val expenses: List<ExpenseItem>,
    val total: Double,
    val status: BudgetStatus = BudgetStatus.PENDING
)

data class Expense(
    val id: String? = null, // Assuming id is optional and generated by the backend
    val category: String,
    val amount: Double,
    val dateOfTransaction: String,
    val comments: String, // Changed from description
    val imagePath: Uri?,
    val createdAt: String
)